package pt.ulisboa.tecnico.cmov.ubibike;

enum NetworkMessageCode {
    LOGIN_USER,
    SIGN_UP_USER,
    TRACK_RIDE,
    CHECK_POINTS,
    GET_HISTORY,
    GET_STATIONS,
    GET_USER_CURRENT_SCORE,
    GET_USER_MOST_RECENT_TRAJECTORY,
    GET_USER_PAST_TRAJECTORIES,
    GET_USER_TRAJECTORIES,
    SEND_POINTS,
    SEND_TRAJECTORY,
    BOOK_BIKE,
    PICK_UP_BIKE,
    DROP_OFF_BIKE,
    RECONNECT_NETWORK,
    RECONNECT_GPS,
    ERROR,
    EXIT
}
