package pt.ulisboa.tecnico.cmov.ubibike;

public enum UserReplyType {
	SUCCESS,
	INVALID_DROP_OFF,
	INVALID_PASSWORD,
	INVALID_USERNAME,
	ALREADY_EXISTS,
	POINTS_MISSMATCH,
	NOT_BOOKED_BIKE,
	NOT_DROPPING_STATION,
	INVALID_REQUEST,
	TECHNICAL_FAILURE,
	INVALID_ENUM;
}
